# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  ## User configs
  - import_tasks: users/binford.yml

  - import_tasks: software/misc_games.yml
  - import_tasks: software/misc_packages.yml
  - import_tasks: software/package_utilities.yml
  - import_tasks: software/steam.yml
  - import_tasks: system_setup/tweaks.yml

  rescue:
    - set_fact: task_failed=true
