- name: system setup | tweaks | add flatpak support
  package:
    name: flatpak
    state: present

- name: system setup | tweaks | flatpak | add flathub remote
  tags: packages,flatpak,workstation-packages
  become_user: jay
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user
    state: present
