---
- name: update_xdg
  tags: users,config,xdg
  become_user: binford
  command: /usr/bin/xdg-user-dirs-update

# GNOME stuff
- name: gnome_tracker_clean_cache
  tags: gnome,tracker
  file:
    path: /home/binford/.cache/tracker
    state: absent

- name: gnome_tracker_clean_local_cache
  tags: gnome,tracker
  file:
    path: /home/binford/.local/share/tracker
    state: absent
